esphome:
  name: bidouille
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_name} Fallback Hotspot"
    password: !secret ap_pwd

captive_portal:

# Enable logging
logger:
  level: VERY_VERBOSE
#  baud_rate: 9600
  baud_rate: 0
#  hardware_uart: UART1

# Enable Home Assistant API
api:

ota:


uart:
#  baud_rate: 115200
  baud_rate: 9600
#  tx_pin: D3
#  rx_pin: D4
  tx_pin: D4
  rx_pin: D3
#  tx_pin: TX
#  rx_pin: RX
  stop_bits: 1

#binary_sensor:
#  - platform: uart
#    name: test_uart


interval:
  - interval: 10s
    then:
#      - uart.write: [0x07, 0x14, 0x00, 0x05, 0x00, 0x34, 0x00, 0x00, 0x11, 0x00, 0x5E]
      - uart.write: [0x07]
# Just 4 test
